version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d # Monta el archivo SQL de inicialización
    networks:
      - my_network

  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - "8080:8080"
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network: